try{
    throw "Invalid";
}
catch(error){
    console.log(error);
}


throw("Invalid")